# omnetpp.ini

[General]
network = TwoNodeQueueing.simulations.TwoNodeNetwork
sim-time-limit = 75000s
repeat = 20
seed-set = ${repetition}
warmup-period = 35000s  

**.source.interArrivalTime = ${4.0s, 5.0s, 6.0s}
**.source.userTypeProbability = ${0.4, 0.6, 0.8}
**.node1.feedbackProbability = ${0.6, 0.8, 0.9}

# Configurazione 1 per i tempi di servizio
[Config1]
description = "Service times config 1"
**.node1.serviceTimeU1_a = 1.4s
**.node1.serviceTimeU1_b = 2.6s
**.node1.serviceTimeU2_c = 1.0s
**.node1.serviceTimeU2_d = 4.0s
**.node2.serviceTimeSS1 = ${2.4s, 3.0s, 3.5s}
**.node2.serviceTimeSS2 = ${2.0s, 3.0s, 4.0s}

# Configurazione 2 per i tempi di servizio
[Config2]
description = "Service times config 2"
**.node1.serviceTimeU1_a = 2.8s
**.node1.serviceTimeU1_b = 3.2s
**.node1.serviceTimeU2_c = 1.8s
**.node1.serviceTimeU2_d = 4.2s
**.node2.serviceTimeSS1 = ${2.4s, 3.0s, 3.5s}
**.node2.serviceTimeSS2 = ${2.0s, 3.0s, 4.0s}


# =========================================================
# FASE 1: Run pilota per analisi transiente - BEST CASE (STABILE)
# =========================================================
#[WarmupPilot_Stable]
#description = "Run pilota per trovare il warmup-period"

# Eredita i tempi di servizio veloci
#extends = Config1

# --- Impostazioni per la singola run pilota ---
#sim-time-limit = 200000s     # Molto lungo
#repeat = 1                   # Una sola run
#warmup-period = 0s           # FONDAMENTALE: partiamo da 0

# ---- Parametri del "Caso Migliore" (carico minimo) ----
#**.source.interArrivalTime = 6.0s      # Tasso di arrivo più basso
#**.source.userTypeProbability = 0.4    # Meno priorità
#**.node1.feedbackProbability = 0.6      # Meno feedback
#**.node2.serviceTimeSS2 = 2.0s          # Servizio SS2 più veloce
#**.node2.serviceTimeSS1 = 2.4s          # Servizio SS1 più veloce