//
// Generated file, do not edit! Created by opp_msgtool 6.1 from Job.msg.
//

#ifndef __JOB_M_H
#define __JOB_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Job;
// cplusplus {{
#include <omnetpp.h>
// }}

/**
 * Class generated from <tt>Job.msg:7</tt> by opp_msgtool.
 * <pre>
 * // Messaggio che rappresenta un utente/job nel sistema
 * message Job
 * {
 *     int type; // 1 per Utente U1, 2 per Utente U2
 *     simtime_t creationTime; // Timestamp di creazione per calcolare il sojourn time
 * }
 * </pre>
 */
class Job : public ::omnetpp::cMessage
{
  protected:
    int type = 0;
    omnetpp::simtime_t creationTime = SIMTIME_ZERO;

  private:
    void copy(const Job& other);

  protected:
    bool operator==(const Job&) = delete;

  public:
    Job(const char *name=nullptr, short kind=0);
    Job(const Job& other);
    virtual ~Job();
    Job& operator=(const Job& other);
    virtual Job *dup() const override {return new Job(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getType() const;
    virtual void setType(int type);

    virtual omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(omnetpp::simtime_t creationTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Job& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Job& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Job *fromAnyPtr(any_ptr ptr) { return check_and_cast<Job*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __JOB_M_H

